const $=s=>document.querySelector(s);let all=[],filter="All";
const grid=$("#appGrid"),trend=$("#trendingGrid"),empty=$("#empty");
async function load(){try{const r=await fetch("/api/apps");all=await r.json();$("#statApps").textContent=all.length;render()}catch(e){all=[];render()}}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function card(a){const icon=a.icon?`<img class="icon" src="${esc(a.icon)}" onerror="this.outerHTML='<div class=icon>K</div>'">`:`<div class="icon">${esc((a.name||"K")[0].toUpperCase())}</div>`;return `<article class="card"><div onclick='openItem(${JSON.stringify(a).replace(/'/g,"&#39;")})'>${icon}<h3>${esc(a.name)}</h3><div class="meta">${esc(a.category)} • v${esc(a.version||"1.0.0")} ${a.size?"• "+esc(a.size):""}</div><p class="desc">${esc(a.description||"Premium app from KIRUU STORE.")}</p><div class="card-bottom"><span>★ ${Number(a.rating||5).toFixed(1)}</span><button class="open">View →</button></div></div></article>`}
function render(){let q=($("#search").value||"").toLowerCase();let items=all.filter(a=>(filter==="All"||a.category===filter)&&`${a.name} ${a.category} ${a.description}`.toLowerCase().includes(q));grid.innerHTML=items.map(card).join("");empty.style.display=items.length?"none":"block";trend.innerHTML=(all.slice().sort((a,b)=>(b.downloads||0)-(a.downloads||0)).slice(0,3)).map(card).join("")||`<div class="empty">Trending apps will appear here.</div>`}
$("#search").addEventListener("input",render);$("#filters").addEventListener("click",e=>{if(e.target.tagName==="BUTTON"){document.querySelectorAll(".filters button").forEach(x=>x.classList.remove("active"));e.target.classList.add("active");filter=e.target.dataset.filter;render()}});
function openItem(a){$("#modalBody").innerHTML=`<div class="icon">${a.icon?`<img class="icon" src="${esc(a.icon)}">`:(a.name||"K")[0]}</div><h2>${esc(a.name)}</h2><p class="meta">${esc(a.category)} • v${esc(a.version||"1.0.0")} • ${esc(a.size||"Size not listed")}</p><p>${esc(a.description||"No description available.")}</p><p class="meta">★ ${Number(a.rating||5).toFixed(1)} • ${Number(a.downloads||0).toLocaleString()} downloads</p>${a.download?`<a class="primary" style="display:inline-block;margin-top:15px" href="${esc(a.download)}">Download ↗</a>`:`<span class="meta">Download link coming soon.</span>`}`;$("#modal").classList.add("show")}
$("#close").onclick=()=>$("#modal").classList.remove("show");$("#modal").onclick=e=>{if(e.target.id==="modal")$("#modal").classList.remove("show")};
new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add("visible")),{threshold:.08}).observe(document.querySelector(".hero"));
document.querySelectorAll(".reveal").forEach(x=>new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add("visible")),{threshold:.08}).observe(x));
load();
